
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include sensors.yaml

# tuya:
#   username: !secret tuya_email
#   password: !secret tuya_password
#   country_code: 1
#   platform: smart_life

media_extractor:

speedtestdotnet:
  scan_interval:
    days: 1
    hours: 0

# ecovacs:
#   username: !secret ecovacs_username
#   password: !secret ecovacs_password
#   country: us
#   continent: na
