
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Use nginx reverse proxy add-on instead to allow unencrypted local traffic
# http:
#   ssl_certificate: /ssl/fullchain.pem
#   ssl_key: /ssl/privkey.pem

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include sensors.yaml

# tuya:
#   username: !secret tuya_email
#   password: !secret tuya_password
#   country_code: 1
#   platform: smart_life

media_extractor:

speedtestdotnet:
  scan_interval:
    days: 1
    hours: 0

# not working yet: perhaps look at:
# https://community.home-assistant.io/t/fixed-ecovacs-deebot-2019-ozmo-series-working-library/126319
# https://github.com/And3rsL/Deebot-for-hassio (HACS)
# ecovacs:
#   username: !secret ecovacs_username
#   password: !secret ecovacs_password
#   country: US
#   continent: NA
